name: deploy_to_dockerhub

on:
  push:
    branches: [ master ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mailclient/backend/mail-client
    steps:
      - name: clone from reporitory
        uses: actions/checkout@v3
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: docker image
        run: |
          ./gradlew dockerBuildMailClientImage 
          docker image ls


      - name: Login to Dockerhub and push
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
        
      - name: Load image
        run: |
          docker image ls
          docker tag mail-client-image:latest smartictsolutions/mailclient:${{ github.run_number }}
          docker tag mail-client-image:latest smartictsolutions/mailclient:latest
          docker image ls -a
          docker push smartictsolutions/mailclient:${{ github.run_number }}
          docker push smartictsolutions/mailclient:latest
